[dev]
  command = "npm run -w converter-app dev"
  port = 8888
  publish = "converter-app/dist"
  framework = "vite"
  targetPort = 5173
  autoLaunch = false

[functions]
  directory = "converter-app/netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "converter-app/src/**"
  ]

[build]
  command = "npm run -w converter-app build"
  publish = "converter-app/dist"
  functions = "converter-app/netlify/functions"